### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by hsmyers** [PacktPublishing/Perl-6-Deep-Dive#1]
Files 8.pl and 9.pl are the same. 9.pl should be the complete grammar and class. This error is the same here and with the download from the main site.

**Comment by deepesh-packt** [comment]
Hey @hsmyers ,
So, that I can look into it. Can you please tell me you found these duplicate files in which chapter?

**Comment by deepesh-packt** [comment]
Please reopen the issue if the issue still persists.
